apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: chuckster456/myapp2:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: myapp2-service
spec:
  selector:
    app: myapp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
