{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .servicePort }}
      targetPort: {{ .containerPort }}
---
{{- end }}
